# Generated by Django 4.1.3 on 2022-11-27 09:01

from django.db import migrations


def populate_my_table(apps, schema_editor):
    Model = apps.get_model("cnab", "TransactionType")
    types = [
        {
            "id": 1,
            "description": "Débito",
            "nature": "Entrada",
        },
        {
            "id": 2,
            "description": "Boleto",
            "nature": "Saída",
        },
        {
            "id": 3,
            "description": "Financiamento",
            "nature": "Saída",
        },
        {
            "id": 4,
            "description": "Crédito",
            "nature": "Entrada",
        },
        {
            "id": 5,
            "description": "Recebimento Empréstimo",
            "nature": "Entrada",
        },
        {
            "id": 6,
            "description": "Vendas",
            "nature": "Entrada",
        },
        {
            "id": 7,
            "description": "Recebimento TED",
            "nature": "Entrada",
        },
        {
            "id": 8,
            "description": "Recebimento DOC",
            "nature": "Entrada",
        },
        {
            "id": 9,
            "description": "Aluguel",
            "nature": "Saída",
        },
    ]
    for typ in types:
        Model.objects.get_or_create(**typ)


class Migration(migrations.Migration):

    dependencies = [
        ("cnab", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_my_table),
    ]


# https://stackoverflow.com/questions/50320989/how-would-you-create-a-manual-django-migration
# https://stackoverflow.com/questions/60161127/django-how-to-populate-table-with-data-migration
