# Generated by Django 4.1.3 on 2022-11-28 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cnab", "0002_auto_20221127_0901"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="date",
            new_name="day",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction",
                to="cnab.transactiontype",
            ),
        ),
    ]
