# Generated by Django 4.1.3 on 2022-11-28 13:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("cnab", "0003_rename_date_transaction_day_alter_transaction_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="transaction",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction",
                to="cnab.store",
            ),
        ),
    ]
