# Generated by Django 4.1.3 on 2022-11-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cnab", "0005_rename_description_store_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="store",
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name="Store",
        ),
    ]
